---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 21814.
--- DateTime: 2026/4/30 16:44
---

if (redis.call('get', KEYS[1]) == ARGV[1]) then
    return redis.call('del', KEYS[1])
end
return 0
